version: "3"
services:
   app:
      ports:
         - "8080:8080"
      build: .
      restart: unless-stopped
      links:
         - mymongodb
      volumes:
         - .:/usr/src/app
   mymongodb: 
      image: mongo
      ports: 
         - "27018:27017"
      restart: unless-stopped
      volumes: 
         - ../data:/data/db

